version: "3"
services:
  ## Sample Application
  sampleapp:
    build:
      context: ./sample-app
      dockerfile: Dockerfile
    container_name: sample-app
    networks:
      - elk-sample
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ./logs:/app/logs

  ## MariaDB to output log
  mariadb:
    image: "mariadb:10.4.13"
    # Include my.ini configurations via commands.
    # command: --sql_mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION,ANSI_QUOTES"
    networks:
      - elk-sample
    ports:
      - "3308:3306"
    # volumes:
    #   - ./data/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "pass#word"
      MYSQL_DATABASE: "sampleapp"
      MYSQL_USER: "sample"
      MYSQL_PASSWORD: "pass#word"
      MYSQL_ALLOW_EMPTY_PASSWORD: "false"

networks:
  elk-sample:

volumes:
  mariadb:
    driver: local